/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductProductIdRouteImport } from './routes/product.$productId'
import { Route as ProductsPageChar123PageChar125RouteImport } from './routes/products.page.{-$page}'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductProductIdRoute = ProductProductIdRouteImport.update({
  id: '/product/$productId',
  path: '/product/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsPageChar123PageChar125Route =
  ProductsPageChar123PageChar125RouteImport.update({
    id: '/products/page/{-$page}',
    path: '/products/page/{-$page}',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/product/$productId': typeof ProductProductIdRoute
  '/products/page/{-$page}': typeof ProductsPageChar123PageChar125Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/product/$productId': typeof ProductProductIdRoute
  '/products/page/{-$page}': typeof ProductsPageChar123PageChar125Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/product/$productId': typeof ProductProductIdRoute
  '/products/page/{-$page}': typeof ProductsPageChar123PageChar125Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/product/$productId' | '/products/page/{-$page}'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/product/$productId' | '/products/page/{-$page}'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/product/$productId'
    | '/products/page/{-$page}'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ProductProductIdRoute: typeof ProductProductIdRoute
  ProductsPageChar123PageChar125Route: typeof ProductsPageChar123PageChar125Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$productId': {
      id: '/product/$productId'
      path: '/product/$productId'
      fullPath: '/product/$productId'
      preLoaderRoute: typeof ProductProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/page/{-$page}': {
      id: '/products/page/{-$page}'
      path: '/products/page/{-$page}'
      fullPath: '/products/page/{-$page}'
      preLoaderRoute: typeof ProductsPageChar123PageChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ProductProductIdRoute: ProductProductIdRoute,
  ProductsPageChar123PageChar125Route: ProductsPageChar123PageChar125Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
